# Autogenerated wrapper script for Usrsctp_jll for aarch64-linux-gnu
export libusrsctp

JLLWrappers.@generate_wrapper_header("Usrsctp")
JLLWrappers.@declare_library_product(libusrsctp, "libusrsctp.so.2")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libusrsctp,
        "lib/libusrsctp.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
